runtime: nodejs
env: flex
beta_settings:
  cloud_sql_instances: buy-and-sell-listings:asia-south1:buy-and-sell-mysqldb
env_variables:
  DB_USER: hapi-server
  DB_PASS: abc123!
  DB_NAME: buy-and-sell
  DB_SOCKET: /cloudsql/buy-and-sell-listings:asia-south1:buy-and-sell-mysqldb